version: "3"
services:
  app:
    container_name: game-api
    restart: always
    build: .    
    ports:
      - "3000:3000"
    links:
      - mongo-docker
    environment:
      - NODE_ENV=docker
  mongo-docker:
    container_name: mongo-docker
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
